printWidth: 150
useTabs: true
tabWidth: 2
semi: true
endOfLine: auto
singleQuote: true
trailingComma: all
bracketSameLine: true
arrowParens: always
proseWrap: always
overrides:
  - files: '*.json'
    options:
      printWidth: 200
  - files: '*.yml'
    options:
      printWidth: 200
      singleQuote: true
  - files: '*.yaml'
    options:
      printWidth: 200
      singleQuote: true
